files:
  ignore: 'node_modules/**/*.*'
# Rule Configuration
rules:
  no-important: 0
  no-ids: 0
  no-vendor-prefixes: 0
  leading-zero: 0
  border-zero: 0
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 2
  nesting-depth:
    - 4
    -
      max-depth: 5
  mixins-before-declarations:
    - 4
    -
      exclude:
        - breakpoint
        - mq

  no-warn: 1
  no-debug: 1
  indentation:
    - 4
    -
      size: 4
  property-sort-order: 0